import pathlib

import pytest

from audit_core import qualify

FIXTURE = pathlib.Path(__file__).resolve().parent / "fixtures" / "target-scores-sample.csv"


def test_load_scores_reads_the_real_columns():
    scores = qualify.load_scores(FIXTURE)
    s = scores[("draytek", "vigor3910")]
    assert s.rce_cves == 49
    assert s.slop_pct == 0.0
    assert s.max_cvss == 9.8
    assert s.first_pub == "2024-09-18"
    assert s.last_pub == "2025-02-27"
    assert s.top_source == "psirt@draytek.com"


def test_find_is_case_insensitive():
    """An operator types `Zyxel` and the CSV holds `zyxel`. Failing that
    lookup would report "not in the scored set" for a model that is."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "ZYXEL", "EMG3525-T50B") is not None
    assert qualify.find(scores, " zyxel ", " emg3525-t50b ") is not None


def test_an_unexpected_header_is_refused_not_read_positionally(tmp_path):
    """Review Focus 2. `_intel/target-scores.csv` is regenerated by someone
    else's scripts. A loader that reads by position would silently score
    slop_pct as max_cvss after a column insert, and report a confident wrong
    verdict. Refusing is the only safe answer."""
    bad = tmp_path / "moved.csv"
    bad.write_text("vendor,model,rce_cves\nzyxel,x,1\n")
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(bad)
    assert "expected columns" in str(exc.value)
    assert "vendor, model, rce_cves, slop_pct" in str(exc.value)


def test_a_missing_file_is_a_clear_error(tmp_path):
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(tmp_path / "nope.csv")
    assert "cannot read" in str(exc.value)


def test_an_unknown_model_returns_none_rather_than_raising():
    """Review Focus 1. The scored set has 1,716 rows and the world has more
    models than that. `find` returning None is what lets the caller report
    NO-GO with a reason, instead of crashing or defaulting to a pass."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "zyxel", "no-such-model") is None
    assert qualify.find(scores, "nosuchvendor", "emg3525-t50b") is None


def test_one_malformed_row_does_not_deny_a_verdict_on_the_others():
    """Review Focus 3. The fixture's last row has `notanumber` for rce_cves
    and an empty slop_pct. All 1,716 real rows parse cleanly today, which is
    precisely why nothing would notice when they stop. One bad row must not
    take the file down."""
    scores = qualify.load_scores(FIXTURE)
    assert ("broken", "row") not in scores
    assert len(scores) == 3
    assert ("draytek", "vigor3910") in scores


def test_truncated_row_is_skipped_not_fatal(tmp_path):
    """A truncated CSV row (missing trailing cells) fills missing cells with
    None. DictReader returns None for missing fields, which raises TypeError
    when passed to int() or float(). This must be skipped, not fatal."""
    truncated = tmp_path / "truncated.csv"
    truncated.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "acme,truncated,5\n"
        "vendor2,model2,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(truncated)
    assert ("acme", "truncated") not in scores
    assert ("vendor2", "model2") in scores
    assert len(scores) == 1


def test_nan_and_inf_are_rejected(tmp_path):
    """NaN and Inf pass float() but are invalid for scoring. A nan would
    make the next filter's check fail-open. Reject non-finite numbers."""
    nan_file = tmp_path / "nan.csv"
    nan_file.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "bad,nan,10,nan,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,inf,10,0.5,inf,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "good,model,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(nan_file)
    assert ("bad", "nan") not in scores
    assert ("bad", "inf") not in scores
    assert ("good", "model") in scores
    assert len(scores) == 1


def test_invalid_numeric_ranges_are_rejected(tmp_path):
    """Negative rce_cves and max_cvss outside 0-10 are impossible. Reject them."""
    invalid = tmp_path / "invalid.csv"
    invalid.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "bad,negative_rce,−1,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,high_cvss,10,0.5,11.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,low_cvss,10,0.5,-0.5,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "good,model,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(invalid)
    assert ("bad", "negative_rce") not in scores
    assert ("bad", "high_cvss") not in scores
    assert ("bad", "low_cvss") not in scores
    assert ("good", "model") in scores
    assert len(scores) == 1


def test_columns_in_different_order_are_refused(tmp_path):
    """A positional reader paired with a lenient header check would pass
    today's tests but silently score the wrong field. Ensure that columns
    in a different order (but with the same set of names) are refused."""
    reordered = tmp_path / "reordered.csv"
    reordered.write_text(
        "model,vendor,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "emg3525-t50b,zyxel,13,0,9.8,2024-05-21,2026-02-24,security@zyxel.com.tw,zyxel.com,CVE-2024-0001\n")
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(reordered)
    assert "wrong order" in str(exc.value)
