import pathlib

import pytest

from audit_core import qualify

FIXTURE = pathlib.Path(__file__).resolve().parent / "fixtures" / "target-scores-sample.csv"


def test_load_scores_reads_the_real_columns():
    scores = qualify.load_scores(FIXTURE)
    s = scores[("draytek", "vigor3910")]
    assert s.rce_cves == 49
    assert s.slop_pct == 0.0
    assert s.max_cvss == 9.8
    assert s.first_pub == "2024-09-18"
    assert s.last_pub == "2025-02-27"
    assert s.top_source == "psirt@draytek.com"


def test_find_is_case_insensitive():
    """An operator types `Zyxel` and the CSV holds `zyxel`. Failing that
    lookup would report "not in the scored set" for a model that is."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "ZYXEL", "EMG3525-T50B") is not None
    assert qualify.find(scores, " zyxel ", " emg3525-t50b ") is not None


def test_an_unexpected_header_is_refused_not_read_positionally(tmp_path):
    """Review Focus 2. `_intel/target-scores.csv` is regenerated by someone
    else's scripts. A loader that reads by position would silently score
    slop_pct as max_cvss after a column insert, and report a confident wrong
    verdict. Refusing is the only safe answer."""
    bad = tmp_path / "moved.csv"
    bad.write_text("vendor,model,rce_cves\nzyxel,x,1\n")
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(bad)
    assert "expected columns" in str(exc.value)
    assert "vendor, model, rce_cves, slop_pct" in str(exc.value)


def test_a_missing_file_is_a_clear_error(tmp_path):
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(tmp_path / "nope.csv")
    assert "cannot read" in str(exc.value)


def test_an_unknown_model_returns_none_rather_than_raising():
    """Review Focus 1. The scored set has 1,716 rows and the world has more
    models than that. `find` returning None is what lets the caller report
    NO-GO with a reason, instead of crashing or defaulting to a pass."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "zyxel", "no-such-model") is None
    assert qualify.find(scores, "nosuchvendor", "emg3525-t50b") is None


def test_one_malformed_row_does_not_deny_a_verdict_on_the_others():
    """Review Focus 3. The fixture's last row has `notanumber` for rce_cves
    and an empty slop_pct. All 1,716 real rows parse cleanly today, which is
    precisely why nothing would notice when they stop. One bad row must not
    take the file down."""
    scores = qualify.load_scores(FIXTURE)
    assert ("broken", "row") not in scores
    assert len(scores) == 3
    assert ("draytek", "vigor3910") in scores
