import pathlib

import pytest

from audit_core import qualify

FIXTURE = pathlib.Path(__file__).resolve().parent / "fixtures" / "target-scores-sample.csv"


def test_load_scores_reads_the_real_columns():
    scores = qualify.load_scores(FIXTURE)
    s = scores[("draytek", "vigor3910")]
    assert s.rce_cves == 49
    assert s.slop_pct == 0.0
    assert s.max_cvss == 9.8
    assert s.first_pub == "2024-09-18"
    assert s.last_pub == "2025-02-27"
    assert s.top_source == "psirt@draytek.com"


def test_find_is_case_insensitive():
    """An operator types `Zyxel` and the CSV holds `zyxel`. Failing that
    lookup would report "not in the scored set" for a model that is."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "ZYXEL", "EMG3525-T50B") is not None
    assert qualify.find(scores, " zyxel ", " emg3525-t50b ") is not None


def test_an_unexpected_header_is_refused_not_read_positionally(tmp_path):
    """Review Focus 2. `_intel/target-scores.csv` is regenerated by someone
    else's scripts. A loader that reads by position would silently score
    slop_pct as max_cvss after a column insert, and report a confident wrong
    verdict. Refusing is the only safe answer."""
    bad = tmp_path / "moved.csv"
    bad.write_text("vendor,model,rce_cves\nzyxel,x,1\n")
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(bad)
    assert "expected columns" in str(exc.value)
    assert "vendor, model, rce_cves, slop_pct" in str(exc.value)


def test_a_missing_file_is_a_clear_error(tmp_path):
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(tmp_path / "nope.csv")
    assert "cannot read" in str(exc.value)


def test_an_unknown_model_returns_none_rather_than_raising():
    """Review Focus 1. The scored set has 1,716 rows and the world has more
    models than that. `find` returning None is what lets the caller report
    NO-GO with a reason, instead of crashing or defaulting to a pass."""
    scores = qualify.load_scores(FIXTURE)
    assert qualify.find(scores, "zyxel", "no-such-model") is None
    assert qualify.find(scores, "nosuchvendor", "emg3525-t50b") is None


def test_one_malformed_row_does_not_deny_a_verdict_on_the_others():
    """Review Focus 3. The fixture's last row has `notanumber` for rce_cves
    and an empty slop_pct. All 1,716 real rows parse cleanly today, which is
    precisely why nothing would notice when they stop. One bad row must not
    take the file down."""
    scores = qualify.load_scores(FIXTURE)
    assert ("broken", "row") not in scores
    assert len(scores) == 3
    assert ("draytek", "vigor3910") in scores


def test_truncated_row_is_skipped_not_fatal(tmp_path):
    """A truncated CSV row (missing trailing cells) fills missing cells with
    None. DictReader returns None for missing fields, which raises TypeError
    when passed to int() or float(). This must be skipped, not fatal."""
    truncated = tmp_path / "truncated.csv"
    truncated.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "acme,truncated,5\n"
        "vendor2,model2,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(truncated)
    assert ("acme", "truncated") not in scores
    assert ("vendor2", "model2") in scores
    assert len(scores) == 1


def test_nan_and_inf_are_rejected(tmp_path):
    """NaN and Inf pass float() but are invalid for scoring. A nan would
    make the next filter's check fail-open. Reject non-finite numbers."""
    nan_file = tmp_path / "nan.csv"
    nan_file.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "bad,nan,10,nan,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,inf,10,0.5,inf,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "good,model,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(nan_file)
    assert ("bad", "nan") not in scores
    assert ("bad", "inf") not in scores
    assert ("good", "model") in scores
    assert len(scores) == 1


def test_invalid_numeric_ranges_are_rejected(tmp_path):
    """Negative rce_cves and max_cvss outside 0-10 are impossible. Reject them."""
    invalid = tmp_path / "invalid.csv"
    invalid.write_text(
        "vendor,model,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "bad,negative_rce,−1,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,high_cvss,10,0.5,11.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "bad,low_cvss,10,0.5,-0.5,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n"
        "good,model,10,0.5,8.0,2024-01-01,2025-01-01,x@y.z,y.z,CVE-2024-0001\n")
    scores = qualify.load_scores(invalid)
    assert ("bad", "negative_rce") not in scores
    assert ("bad", "high_cvss") not in scores
    assert ("bad", "low_cvss") not in scores
    assert ("good", "model") in scores
    assert len(scores) == 1


def test_columns_in_different_order_are_refused(tmp_path):
    """A positional reader paired with a lenient header check would pass
    today's tests but silently score the wrong field. Ensure that columns
    in a different order (but with the same set of names) are refused."""
    reordered = tmp_path / "reordered.csv"
    reordered.write_text(
        "model,vendor,rce_cves,slop_pct,max_cvss,first_pub,last_pub,top_source,top_ref_hosts,sample_cves\n"
        "emg3525-t50b,zyxel,13,0,9.8,2024-05-21,2026-02-24,security@zyxel.com.tw,zyxel.com,CVE-2024-0001\n")
    with pytest.raises(qualify.QualifyError) as exc:
        qualify.load_scores(reordered)
    assert "wrong order" in str(exc.value)


# Task 2: The three filters


def test_proven_bad_accepts_a_span_overlapping_2024_2025():
    scores = qualify.load_scores(FIXTURE)
    r = qualify.filter_proven_bad(scores[("zyxel", "emg3525-t50b")])
    assert r.passed is True
    assert r.name == "proven-bad"


def test_low_slop_is_an_AND_not_a_cve_threshold():
    """DrayTek Vigor3910 has 49 RCE CVEs - well over the 20 threshold - at 0%
    VulDB, and the hunting plan lists it as Tier A ("hunt these"). A filter
    that rejected it on CVE count alone would throw away the plan's second-
    best target. Tenda AC18, 51 CVEs at 67%, is the one to reject."""
    scores = qualify.load_scores(FIXTURE)
    high_cve_low_slop = qualify.filter_low_slop(scores[("draytek", "vigor3910")])
    assert high_cve_low_slop.passed is True

    strip_mined = qualify.filter_low_slop(scores[("tenda", "ac18")])
    assert strip_mined.passed is False
    assert "strip-mined" in strip_mined.reason


def test_proven_bad_rejects_a_span_entirely_after_the_window():
    s = qualify.Score(vendor="x", model="y", rce_cves=5, slop_pct=0.0,
                      max_cvss=9.8, first_pub="2026-01-02",
                      last_pub="2026-09-30", top_source="psirt@x.z")
    r = qualify.filter_proven_bad(s)
    assert r.passed is False
    assert "does not reach" in r.reason


def test_support_evidence_must_point_at_something_checkable():
    """The rule this filter exists for. `check_identity_evidence` ALONE
    accepts "Zyxel NWA50AX is supported" - verified 2026-10-07 - because
    `supported` counts as a novel token. A claim that restates its own
    conclusion is not evidence."""
    circular = qualify.filter_supported(
        "zyxel", "nwa50ax", True, "Zyxel NWA50AX is supported")
    assert circular.passed is False

    checkable = qualify.filter_supported(
        "zyxel", "nwa50ax", True,
        "advisory ZYXEL-SA-2026-02 issued 2026-02-14 for this SKU")
    assert checkable.passed is True


def test_declaring_a_target_unsupported_needs_no_evidence():
    """Review Focus 5. NO-GO is already the safe direction. Requiring good
    evidence to decline would push an operator toward asserting `yes`, which
    inverts the whole point of the filter."""
    r = qualify.filter_supported("tenda", "ac18", False, "")
    assert r.passed is False
    assert "not supported" in r.reason


def test_vague_support_claims_are_all_rejected():
    for vague in ("supported, still shipping firmware",
                  "the vendor says it is supported and current",
                  "it is definitely still a current product line"):
        r = qualify.filter_supported("zyxel", "nwa50ax", True, vague)
        assert r.passed is False, f"accepted vague evidence: {vague!r}"


def test_a_hostname_or_a_version_is_also_checkable():
    for good in ("EoS listing at zyxel.com shows no end-of-support date",
                 "firmware 5.21 released for this model, per the vendor"):
        r = qualify.filter_supported("zyxel", "nwa50ax", True, good)
        assert r.passed is True, f"rejected checkable evidence: {good!r}"


GOOD_EVIDENCE = "advisory ZYXEL-SA-2026-02 issued 2026-02-14 for this SKU"


def test_a_target_passing_all_three_filters_is_GO():
    scores = qualify.load_scores(FIXTURE)
    q = qualify.qualify(scores, "zyxel", "emg3525-t50b", True, GOOD_EVIDENCE)
    assert q.verdict == qualify.GO
    assert q.go is True
    assert all(f.passed for f in q.filters)


def test_one_failing_filter_is_enough_for_NOGO():
    scores = qualify.load_scores(FIXTURE)
    q = qualify.qualify(scores, "tenda", "ac18", True, GOOD_EVIDENCE)
    assert q.verdict == qualify.NOGO
    assert [f.name for f in q.filters if not f.passed] == ["low-slop"]


def test_an_unknown_model_is_NOGO_with_a_reason_not_a_crash():
    """Review Focus 1, end to end. Both data-backed filters report the same
    cause, and the verdict is NO-GO rather than a default pass."""
    scores = qualify.load_scores(FIXTURE)
    q = qualify.qualify(scores, "zyxel", "no-such-model", True, GOOD_EVIDENCE)
    assert q.verdict == qualify.NOGO
    assert q.score is None
    reasons = {f.name: f.reason for f in q.filters if not f.passed}
    assert reasons["proven-bad"] == "not in the scored target set"
    assert reasons["low-slop"] == "not in the scored target set"
    assert "not in the scored target set" in qualify.render(q)


# FINDING 1: Model names can satisfy CHECKABLE
def test_a_model_whose_own_name_is_checkable_cannot_self_certify():
    """Exactly one real model, tenda/o3_firmware1.0.0.10\\(2478\\), has a
    name containing a dotted number. Evidence that merely repeats vendor
    and model must still FAIL - the name is not a handle the operator
    supplied."""
    vendor = "tenda"
    model = "o3_firmware1.0.0.10\\(2478\\)"
    r = qualify.filter_supported(vendor, model, True,
                                 f"{vendor} {model} is supported")
    assert r.passed is False
    assert "checkable" in r.reason


def test_model_name_in_evidence_does_not_make_it_checkable():
    """A simpler model name case: truncated version without special chars."""
    r = qualify.filter_supported(
        "tenda", "o3_firmware1.0.0.10", True,
        "tenda o3_firmware1.0.0.10 is supported")
    assert r.passed is False
    assert "checkable" in r.reason


# FINDING 2: Irrelevant handles (CVSS, CVE IDs) must be stripped
def test_cvss_score_in_evidence_does_not_satisfy_checkable():
    """CVSS scores and CVE IDs are not evidence of support. We strip them
    before checking CHECKABLE, so 'CVSS 9.8 confirms this' must FAIL."""
    r = qualify.filter_supported(
        "example", "model", True,
        "CVSS 9.8 confirms this is supported")
    assert r.passed is False
    assert "checkable" in r.reason


def test_cve_id_in_evidence_does_not_satisfy_checkable():
    """CVE IDs are stripped as non-support patterns."""
    r = qualify.filter_supported(
        "example", "model", True,
        "CVE-2024-12345 shows it is still supported")
    assert r.passed is False
    assert "checkable" in r.reason


def test_scoring_pattern_is_stripped():
    """Scoring patterns like 'score 9.8' are stripped as non-support."""
    r = qualify.filter_supported(
        "example", "model", True,
        "score 9.8 indicates this model is supported")
    assert r.passed is False
    assert "checkable" in r.reason


# FINDING 3: Version patterns with 'v' prefix
def test_version_with_v_prefix_is_checkable():
    """Versions like v5.21 should match. The pattern now includes \\bv?."""
    r = qualify.filter_supported(
        "zyxel", "nwa50ax", True,
        "firmware v5.21 released for this model, per the vendor")
    assert r.passed is True


# FINDING 4: Filter 2 boundary cases
def test_filter_low_slop_boundary_exactly_20_cves_at_high_slop():
    """Exactly 20 CVEs (not > 20) at 99% slop should PASS."""
    s = qualify.Score(vendor="x", model="y", rce_cves=20, slop_pct=99.0,
                      max_cvss=9.8, first_pub="2024-01-01",
                      last_pub="2025-12-31", top_source="psirt@x.z")
    r = qualify.filter_low_slop(s)
    assert r.passed is True


def test_filter_low_slop_boundary_many_cves_at_exactly_50_slop():
    """99 CVEs at exactly 50.0% slop (not > 50) should PASS."""
    s = qualify.Score(vendor="x", model="y", rce_cves=99, slop_pct=50.0,
                      max_cvss=9.8, first_pub="2024-01-01",
                      last_pub="2025-12-31", top_source="psirt@x.z")
    r = qualify.filter_low_slop(s)
    assert r.passed is True


def test_filter_low_slop_boundary_just_over_threshold():
    """21 CVEs at 50.1% slop (both > threshold) should FAIL."""
    s = qualify.Score(vendor="x", model="y", rce_cves=21, slop_pct=50.1,
                      max_cvss=9.8, first_pub="2024-01-01",
                      last_pub="2025-12-31", top_source="psirt@x.z")
    r = qualify.filter_low_slop(s)
    assert r.passed is False
    assert "strip-mined" in r.reason


# FINDING 5: Bad dates produce NO-GO without crashing
def test_proven_bad_with_empty_date():
    """Empty date field causes lexicographic comparison to fail safely."""
    s = qualify.Score(vendor="x", model="y", rce_cves=5, slop_pct=0.0,
                      max_cvss=9.8, first_pub="",
                      last_pub="2025-12-31", top_source="psirt@x.z")
    r = qualify.filter_proven_bad(s)
    assert r.passed is False
    assert "does not reach" in r.reason


def test_proven_bad_with_garbage_date_format():
    """Non-ISO dates still compare but produce NO-GO."""
    s = qualify.Score(vendor="x", model="y", rce_cves=5, slop_pct=0.0,
                      max_cvss=9.8, first_pub="garbage",
                      last_pub="also-garbage", top_source="psirt@x.z")
    r = qualify.filter_proven_bad(s)
    assert r.passed is False


# FINDING 6: Test to_json
def test_to_json_emits_primitives_not_objects():
    """to_json must serialize Score as a dict, not an object."""
    scores = qualify.load_scores(FIXTURE)
    q = qualify.qualify(scores, "zyxel", "emg3525-t50b", True, GOOD_EVIDENCE)
    payload = qualify.to_json(q)

    # Check structure
    assert isinstance(payload, dict)
    assert payload["vendor"] == "zyxel"
    assert payload["model"] == "emg3525-t50b"
    assert payload["verdict"] == "GO"

    # Score should be a dict with primitives
    assert isinstance(payload["score"], dict)
    assert isinstance(payload["score"]["rce_cves"], int)
    assert isinstance(payload["score"]["slop_pct"], float)
    assert isinstance(payload["score"]["max_cvss"], float)
    assert isinstance(payload["score"]["first_pub"], str)

    # Filters should be dicts
    assert isinstance(payload["filters"], list)
    assert all(isinstance(f, dict) for f in payload["filters"])
    assert all("name" in f and "passed" in f and "reason" in f for f in payload["filters"])


def test_to_json_with_no_score():
    """to_json must not crash when score is None."""
    scores = qualify.load_scores(FIXTURE)
    q = qualify.qualify(scores, "unknown", "model", True, GOOD_EVIDENCE)
    payload = qualify.to_json(q)

    assert payload["score"] is None
    assert payload["vendor"] == "unknown"
    assert payload["verdict"] == "NO-GO"
