"""Decide whether a firmware target is worth auditing, before the audit runs.

The hunting plan's three filters, in order of how expensive it is to get them
wrong: a proven-bad codebase, low mining pressure, and - the binding one - a
vendor that still supports the SKU. "A week of work on an EOS SKU pays zero",
and in token terms an EOL SKU pays zero and costs thousands.

So this module exists to say NO cheaply. Every filter fails closed: absent
data, an absent assertion, and unverifiable evidence are all NO-GO, never a
warning and never a default pass. A false NO-GO costs one re-run with better
evidence; a false GO costs a week.

Nothing here writes anything. It reads one CSV and returns a verdict.
"""
from __future__ import annotations

import csv
import math
import pathlib
import re
from dataclasses import dataclass

from audit_core import db


class QualifyError(Exception):
    """The scored-target file cannot be read or is not the expected shape."""


EXPECTED_HEADER: tuple[str, ...] = (
    "vendor", "model", "rce_cves", "slop_pct", "max_cvss",
    "first_pub", "last_pub", "top_source", "top_ref_hosts", "sample_cves")
"""The header of `_intel/target-scores.csv` as of 2026-10-07.

Validated on load rather than assumed. That file is regenerated by the scripts
in `_intel/scripts`, so its shape can move without anyone here noticing - and
a loader that reads columns positionally would then silently score the wrong
field, which is worse than refusing to run.
"""


@dataclass(frozen=True, slots=True)
class Score:
    vendor: str
    model: str
    rce_cves: int
    slop_pct: float
    max_cvss: float
    first_pub: str
    last_pub: str
    top_source: str


def load_scores(path: str | pathlib.Path) -> dict[tuple[str, str], Score]:
    """Read the scored-target CSV into a (vendor, model) index.

    A row whose numbers do not parse is SKIPPED, not fatal. The file holds
    1,716 rows regenerated by someone else's scripts; one bad row must not
    deny the operator a verdict on an unrelated model. A malformed HEADER is
    fatal, because that means every row is being misread.
    """
    path = pathlib.Path(path)
    try:
        handle = path.open(newline="", encoding="utf-8-sig")
    except OSError as exc:
        raise QualifyError(f"cannot read {path}: {exc}") from exc

    with handle:
        try:
            reader = csv.DictReader(handle)
            actual = tuple(reader.fieldnames or ())
        except (UnicodeDecodeError, csv.Error) as exc:
            raise QualifyError(f"cannot read {path}: {exc}") from exc

        if actual != EXPECTED_HEADER:
            # Check if sets match but order differs
            if set(actual) == set(EXPECTED_HEADER):
                raise QualifyError(
                    f"{path} has the right columns in the wrong order.\n"
                    f"  expected order: {', '.join(EXPECTED_HEADER)}\n"
                    f"  found order:    {', '.join(actual)}")
            else:
                # Sets don't match - show expected, found, and what's missing/unexpected
                expected_set = set(EXPECTED_HEADER)
                actual_set = set(actual)
                missing = expected_set - actual_set
                unexpected = actual_set - expected_set
                msg = f"{path} does not have the expected columns.\n"
                msg += f"  expected: {', '.join(EXPECTED_HEADER)}\n"
                msg += f"  found:    {', '.join(actual) or '(no header)'}"
                if missing:
                    msg += f"\n  missing: {', '.join(sorted(missing))}"
                if unexpected:
                    msg += f"\n  unexpected: {', '.join(sorted(unexpected))}"
                raise QualifyError(msg)

        out: dict[tuple[str, str], Score] = {}
        try:
            for row in reader:
                try:
                    rce_cves = int(row["rce_cves"])
                    slop_pct = float(row["slop_pct"])
                    max_cvss = float(row["max_cvss"])

                    # Reject impossible values; fail closed on every check
                    if rce_cves < 0:
                        continue
                    if not (0 <= max_cvss <= 10):
                        continue
                    if not math.isfinite(slop_pct):
                        continue
                    if not math.isfinite(max_cvss):
                        continue

                    score = Score(
                        vendor=row["vendor"].strip().lower(),
                        model=row["model"].strip().lower(),
                        rce_cves=rce_cves,
                        slop_pct=slop_pct,
                        max_cvss=max_cvss,
                        first_pub=row["first_pub"].strip(),
                        last_pub=row["last_pub"].strip(),
                        top_source=row["top_source"].strip())
                except (ValueError, TypeError, AttributeError, KeyError):
                    continue
                out[(score.vendor, score.model)] = score
        except (UnicodeDecodeError, csv.Error) as exc:
            raise QualifyError(f"cannot read {path}: {exc}") from exc
    return out


def find(scores: dict[tuple[str, str], Score],
         vendor: str, model: str) -> Score | None:
    """Case-insensitive lookup. None when the model is not in the scored set."""
    return scores.get((vendor.strip().lower(), model.strip().lower()))


GO = "GO"
NOGO = "NO-GO"

WINDOW_START = "2024-01-01"
WINDOW_END = "2025-12-31"
"""The pre-AI-slop CVE window, from the hunting plan's filter 1:
"a real RCE CVE in 2024-2025 (not 2026; pre-AI-slop lineage)"."""

MAX_CVES_WHEN_SLOPPY = 20
MAX_SLOP_PCT = 50.0
"""Tier C, verbatim: "Anything with >20 CVEs and >50% VulDB."

BOTH conditions, which is the whole point. DrayTek has 49 RCE CVEs at 0% slop
and is a Tier A target; a CVE-count threshold alone would reject it.
"""


@dataclass(frozen=True, slots=True)
class FilterResult:
    name: str
    passed: bool
    reason: str


def filter_proven_bad(score: Score | None) -> FilterResult:
    """Filter 1: the model's CVE span overlaps 2024-2025.

    An interval-overlap test, not "first_pub is in 2024", because that is what
    `first_pub` and `last_pub` can honestly support. A model whose CVEs run
    2023 to 2025 has pre-slop lineage; one whose CVEs are all 2026 does not.
    Dates are ISO-8601, so string comparison is date comparison.
    """
    if score is None:
        return FilterResult("proven-bad", False,
                            "not in the scored target set")
    if score.rce_cves < 1:
        return FilterResult("proven-bad", False, "no RCE CVEs on record")
    # Fail closed on missing or malformed dates; empty string is not a date.
    if not score.first_pub or not score.last_pub:
        return FilterResult(
            "proven-bad", False,
            f"CVE span {score.first_pub or '(missing)'}..{score.last_pub or '(missing)'} "
            f"does not reach {WINDOW_START}..{WINDOW_END}")
    overlaps = score.first_pub <= WINDOW_END and score.last_pub >= WINDOW_START
    if not overlaps:
        return FilterResult(
            "proven-bad", False,
            f"CVE span {score.first_pub}..{score.last_pub} does not reach "
            f"{WINDOW_START}..{WINDOW_END}")
    return FilterResult(
        "proven-bad", True,
        f"{score.rce_cves} RCE CVE(s), span {score.first_pub}..{score.last_pub}")


def filter_low_slop(score: Score | None) -> FilterResult:
    """Filter 2: not strip-mined by the CVE paper mills."""
    if score is None:
        return FilterResult("low-slop", False, "not in the scored target set")
    if score.rce_cves > MAX_CVES_WHEN_SLOPPY and score.slop_pct > MAX_SLOP_PCT:
        return FilterResult(
            "low-slop", False,
            f"{score.rce_cves} CVEs at {score.slop_pct:g}% VulDB - "
            f"strip-mined (Tier C: >{MAX_CVES_WHEN_SLOPPY} CVEs AND "
            f">{MAX_SLOP_PCT:g}% VulDB)")
    return FilterResult(
        "low-slop", True,
        f"{score.rce_cves} CVEs at {score.slop_pct:g}% VulDB, top source "
        f"{score.top_source or 'unknown'}")


CHECKABLE = re.compile(
    r"\b(?:19|20)\d{2}\b"                          # a four-digit year
    r"|\bv?\d+\.\d+(?:\.\d+)*\b"                   # a dotted version (with optional v prefix)
    r"|\b[a-z0-9-]+\.(?:com|net|org|tw|io|cn)\b",  # a hostname
    re.I)
"""Evidence must point at something a reader can go and verify—a verifiable
handle, not proof.

`db.check_identity_evidence` alone is NOT sufficient here, and that was
measured rather than assumed: on 2026-10-07 it ACCEPTED "Zyxel NWA50AX is
supported", because `supported` is a token the subject's name does not
contain. A support claim that restates its own conclusion passes a
novel-token test and tells a later reader nothing. Further, the model name
itself (e.g., "tenda o3_firmware1.0.0.10(2478)") can match a dotted version.

A year, a version number, or a hostname gives a reader of a GO decision
somewhere to look. CHECKABLE tests whether the evidence NAMES something
checkable, not whether that thing actually supports the claim. This is the
floor: the evidence must be concrete enough to verify or disprove.
"""


def filter_supported(vendor: str, model: str, supported: bool,
                     evidence: str) -> FilterResult:
    """Filter 3, the binding one, with no data behind it.

    Two checks, because the first alone lets a circular claim through:
    `db.check_identity_evidence` for the length and novel-token floor already
    used by `audit.py identify`, then `CHECKABLE` for a verifiable handle
    after stripping the vendor/model and non-support patterns.

    Declining needs no evidence. An operator who says the SKU is NOT supported
    has already reached the safe answer, and demanding justification for it
    would push people toward asserting `yes`.
    """
    if not supported:
        return FilterResult("supported", False,
                            "operator declared the SKU not supported")

    subject = f"{vendor}/{model}"
    try:
        db.check_identity_evidence(subject, evidence or "")
    except db.DbError as exc:
        return FilterResult("supported", False, str(exc))

    # Strip vendor/model and non-support patterns to prevent circular claims
    # and irrelevant handles from passing.
    stripped = evidence

    # Remove vendor and model names (case-insensitive) when they are NOT
    # immediately followed by a dot (to avoid breaking domain names like
    # zyxel.com). This handles models ending in non-word chars like ).
    stripped = re.sub(rf"{re.escape(vendor)}(?![\w.])", "", stripped, flags=re.I)
    stripped = re.sub(rf"{re.escape(model)}(?![\w.])", "", stripped, flags=re.I)

    # Remove non-support patterns: CVSS scores, CVE IDs, scoring patterns
    stripped = re.sub(r"cvss\s*v?\d+(?:\.\d+)?", "", stripped, flags=re.I)
    stripped = re.sub(r"CVE-\d{4}-\d+", "", stripped)
    stripped = re.sub(r"score\s*\d+\.\d+", "", stripped, flags=re.I)

    if not CHECKABLE.search(stripped):
        return FilterResult(
            "supported", False,
            "evidence names nothing checkable - cite a date, a firmware "
            "version, or a vendor host, so a later reader can verify this "
            "GO rather than trust it")
    return FilterResult("supported", True, evidence.strip())


@dataclass(frozen=True, slots=True)
class Qualification:
    vendor: str
    model: str
    score: Score | None
    filters: tuple[FilterResult, ...]
    verdict: str

    @property
    def go(self) -> bool:
        return self.verdict == GO


def qualify(scores: dict[tuple[str, str], Score], vendor: str, model: str,
            supported: bool, evidence: str) -> Qualification:
    """All three filters. GO only when every one passes."""
    score = find(scores, vendor, model)
    filters = (
        filter_proven_bad(score),
        filter_low_slop(score),
        filter_supported(vendor, model, supported, evidence),
    )
    verdict = GO if all(f.passed for f in filters) else NOGO
    return Qualification(vendor=vendor, model=model, score=score,
                         filters=filters, verdict=verdict)


def render(q: Qualification) -> str:
    out = [f"qualify {q.vendor}/{q.model}: {q.verdict}"]
    if q.score is None:
        out.append("  (not in the scored target set)")
    for f in q.filters:
        mark = "pass" if f.passed else "FAIL"
        out.append(f"  {mark}  {f.name:<12} {f.reason}")
    if not q.go:
        out.append("")
        out.append("  NO-GO. An EOL or strip-mined SKU pays zero and costs "
                   "thousands of tokens; this gate exists to say so before "
                   "the pipeline starts.")
    return "\n".join(out)


def to_json(q: Qualification) -> dict:
    return {
        "vendor": q.vendor,
        "model": q.model,
        "verdict": q.verdict,
        "filters": [{"name": f.name, "passed": f.passed, "reason": f.reason}
                    for f in q.filters],
        "score": None if q.score is None else {
            "rce_cves": q.score.rce_cves, "slop_pct": q.score.slop_pct,
            "max_cvss": q.score.max_cvss, "first_pub": q.score.first_pub,
            "last_pub": q.score.last_pub, "top_source": q.score.top_source},
    }
