"""Decide whether a firmware target is worth auditing, before the audit runs.

The hunting plan's three filters, in order of how expensive it is to get them
wrong: a proven-bad codebase, low mining pressure, and - the binding one - a
vendor that still supports the SKU. "A week of work on an EOS SKU pays zero",
and in token terms an EOL SKU pays zero and costs thousands.

So this module exists to say NO cheaply. Every filter fails closed: absent
data, an absent assertion, and unverifiable evidence are all NO-GO, never a
warning and never a default pass. A false NO-GO costs one re-run with better
evidence; a false GO costs a week.

Nothing here writes anything. It reads one CSV and returns a verdict.
"""
from __future__ import annotations

import csv
import math
import pathlib
from dataclasses import dataclass


class QualifyError(Exception):
    """The scored-target file cannot be read or is not the expected shape."""


EXPECTED_HEADER: tuple[str, ...] = (
    "vendor", "model", "rce_cves", "slop_pct", "max_cvss",
    "first_pub", "last_pub", "top_source", "top_ref_hosts", "sample_cves")
"""The header of `_intel/target-scores.csv` as of 2026-10-07.

Validated on load rather than assumed. That file is regenerated by the scripts
in `_intel/scripts`, so its shape can move without anyone here noticing - and
a loader that reads columns positionally would then silently score the wrong
field, which is worse than refusing to run.
"""


@dataclass(frozen=True, slots=True)
class Score:
    vendor: str
    model: str
    rce_cves: int
    slop_pct: float
    max_cvss: float
    first_pub: str
    last_pub: str
    top_source: str


def load_scores(path: str | pathlib.Path) -> dict[tuple[str, str], Score]:
    """Read the scored-target CSV into a (vendor, model) index.

    A row whose numbers do not parse is SKIPPED, not fatal. The file holds
    1,716 rows regenerated by someone else's scripts; one bad row must not
    deny the operator a verdict on an unrelated model. A malformed HEADER is
    fatal, because that means every row is being misread.
    """
    path = pathlib.Path(path)
    try:
        handle = path.open(newline="", encoding="utf-8-sig")
    except OSError as exc:
        raise QualifyError(f"cannot read {path}: {exc}") from exc

    with handle:
        try:
            reader = csv.DictReader(handle)
            actual = tuple(reader.fieldnames or ())
        except (UnicodeDecodeError, csv.Error) as exc:
            raise QualifyError(f"cannot read {path}: {exc}") from exc

        if actual != EXPECTED_HEADER:
            # Check if sets match but order differs
            if set(actual) == set(EXPECTED_HEADER):
                raise QualifyError(
                    f"{path} has the right columns in the wrong order.\n"
                    f"  expected order: {', '.join(EXPECTED_HEADER)}\n"
                    f"  found order:    {', '.join(actual)}")
            else:
                # Sets don't match - show expected, found, and what's missing/unexpected
                expected_set = set(EXPECTED_HEADER)
                actual_set = set(actual)
                missing = expected_set - actual_set
                unexpected = actual_set - expected_set
                msg = f"{path} does not have the expected columns.\n"
                msg += f"  expected: {', '.join(EXPECTED_HEADER)}\n"
                msg += f"  found:    {', '.join(actual) or '(no header)'}"
                if missing:
                    msg += f"\n  missing: {', '.join(sorted(missing))}"
                if unexpected:
                    msg += f"\n  unexpected: {', '.join(sorted(unexpected))}"
                raise QualifyError(msg)

        out: dict[tuple[str, str], Score] = {}
        try:
            for row in reader:
                try:
                    rce_cves = int(row["rce_cves"])
                    slop_pct = float(row["slop_pct"])
                    max_cvss = float(row["max_cvss"])

                    # Reject impossible values; fail closed on every check
                    if rce_cves < 0:
                        continue
                    if not (0 <= max_cvss <= 10):
                        continue
                    if not math.isfinite(slop_pct):
                        continue
                    if not math.isfinite(max_cvss):
                        continue

                    score = Score(
                        vendor=row["vendor"].strip().lower(),
                        model=row["model"].strip().lower(),
                        rce_cves=rce_cves,
                        slop_pct=slop_pct,
                        max_cvss=max_cvss,
                        first_pub=row["first_pub"].strip(),
                        last_pub=row["last_pub"].strip(),
                        top_source=row["top_source"].strip())
                except (ValueError, TypeError, AttributeError, KeyError):
                    continue
                out[(score.vendor, score.model)] = score
        except (UnicodeDecodeError, csv.Error) as exc:
            raise QualifyError(f"cannot read {path}: {exc}") from exc
    return out


def find(scores: dict[tuple[str, str], Score],
         vendor: str, model: str) -> Score | None:
    """Case-insensitive lookup. None when the model is not in the scored set."""
    return scores.get((vendor.strip().lower(), model.strip().lower()))
